// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBECLABGFnESbHLj5d2F_aYvV_urtJNUl8',
    appId: '1:967341367732:web:c32f31fa79edb0219a92e1',
    messagingSenderId: '967341367732',
    projectId: 'insta-clone-f2e8d',
    authDomain: 'insta-clone-f2e8d.firebaseapp.com',
    storageBucket: 'insta-clone-f2e8d.appspot.com',
    measurementId: 'G-29474F8YQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGEcSXeZBx66lX8txUSBH_9rVIRvam1v4',
    appId: '1:967341367732:android:46eec2ae8059abb19a92e1',
    messagingSenderId: '967341367732',
    projectId: 'insta-clone-f2e8d',
    storageBucket: 'insta-clone-f2e8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArsTLF9EXP8udwEp8OjT5kOPEhMu1yqxc',
    appId: '1:967341367732:ios:ff79b76abd43cb2a9a92e1',
    messagingSenderId: '967341367732',
    projectId: 'insta-clone-f2e8d',
    storageBucket: 'insta-clone-f2e8d.appspot.com',
    iosClientId: '967341367732-gppm15u69758krutetosp6n2tt4f0bu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArsTLF9EXP8udwEp8OjT5kOPEhMu1yqxc',
    appId: '1:967341367732:ios:ff79b76abd43cb2a9a92e1',
    messagingSenderId: '967341367732',
    projectId: 'insta-clone-f2e8d',
    storageBucket: 'insta-clone-f2e8d.appspot.com',
    iosClientId: '967341367732-gppm15u69758krutetosp6n2tt4f0bu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
